package com.consulmedics.patientdata.scardlib;

public class WinDefs {
    public static final int LibraryVersion = 1;
    public static final long SCARD_S_SUCCESS = 0L;
    public static final long INFINITE = -1L;
    public static final long IOCTL_CCID_ESCAPE = Defs.SCARD_CTL_CODE(3500);
    public static final long SCARD_PROTOCOL_UNDEFINED = 0L;
    public static final long SCARD_PROTOCOL_T0 = 1L;
    public static final long SCARD_PROTOCOL_T1 = 2L;
    public static final long SCARD_PROTOCOL_RAW = 65536L;
    public static final long SCARD_PROTOCOL_TX = 3L;
    public static final long SCARD_PROTOCOL_DEFAULT = -2147483648L;
    public static final long SCARD_PROTOCOL_OPTIMAL = 0L;
    public static final int SCARD_UNKNOWN = 0;
    public static final int SCARD_ABSENT = 1;
    public static final int SCARD_PRESENT = 2;
    public static final int SCARD_SWALLOWED = 3;
    public static final int SCARD_POWERED = 4;
    public static final int SCARD_NEGOTIABLE = 5;
    public static final int SCARD_SPECIFIC = 6;
    public static final int SCARD_STATE_UNAWARE = 0;
    public static final int SCARD_STATE_IGNORE = 1;
    public static final int SCARD_STATE_CHANGED = 2;
    public static final int SCARD_STATE_UNKNOWN = 4;
    public static final int SCARD_STATE_UNAVAILABLE = 8;
    public static final int SCARD_STATE_EMPTY = 16;
    public static final int SCARD_STATE_PRESENT = 32;
    public static final int SCARD_STATE_ATRMATCH = 64;
    public static final int SCARD_STATE_EXCLUSIVE = 128;
    public static final int SCARD_STATE_INUSE = 256;
    public static final int SCARD_STATE_MUTE = 512;
    public static final int SCARD_STATE_UNPOWERED = 1024;
    public static final int SCARD_ATTR_VENDOR_NAME;
    public static final int SCARD_ATTR_VENDOR_IFD_TYPE;
    public static final int SCARD_ATTR_VENDOR_IFD_VERSION;
    public static final int SCARD_ATTR_VENDOR_IFD_SERIAL_NO;
    public static final int SCARD_ATTR_CHANNEL_ID;
    public static final int SCARD_ATTR_PROTOCOL_TYPES;
    public static final int SCARD_ATTR_DEFAULT_CLK;
    public static final int SCARD_ATTR_MAX_CLK;
    public static final int SCARD_ATTR_DEFAULT_DATA_RATE;
    public static final int SCARD_ATTR_MAX_DATA_RATE;
    public static final int SCARD_ATTR_MAX_IFSD;
    public static final int SCARD_ATTR_POWER_MGMT_SUPPORT;
    public static final int SCARD_ATTR_USER_TO_CARD_AUTH_DEVICE;
    public static final int SCARD_ATTR_USER_AUTH_INPUT_DEVICE;
    public static final int SCARD_ATTR_CHARACTERISTICS;
    public static final int SCARD_ATTR_CURRENT_PROTOCOL_TYPE;
    public static final int SCARD_ATTR_CURRENT_CLK;
    public static final int SCARD_ATTR_CURRENT_F;
    public static final int SCARD_ATTR_CURRENT_D;
    public static final int SCARD_ATTR_CURRENT_N;
    public static final int SCARD_ATTR_CURRENT_W;
    public static final int SCARD_ATTR_CURRENT_IFSC;
    public static final int SCARD_ATTR_CURRENT_IFSD;
    public static final int SCARD_ATTR_CURRENT_BWT;
    public static final int SCARD_ATTR_CURRENT_CWT;
    public static final int SCARD_ATTR_CURRENT_EBC_ENCODING;
    public static final int SCARD_ATTR_EXTENDED_BWT;
    public static final int SCARD_ATTR_ICC_PRESENCE;
    public static final int SCARD_ATTR_ICC_INTERFACE_STATUS;
    public static final int SCARD_ATTR_CURRENT_IO_STATE;
    public static final int SCARD_ATTR_ATR_STRING;
    public static final int SCARD_ATTR_ICC_TYPE_PER_ATR;
    public static final int SCARD_ATTR_ESC_RESET;
    public static final int SCARD_ATTR_ESC_CANCEL;
    public static final int SCARD_ATTR_ESC_AUTHREQUEST;
    public static final int SCARD_ATTR_MAXINPUT;
    public static final int SCARD_ATTR_DEVICE_UNIT;
    public static final int SCARD_ATTR_DEVICE_IN_USE;
    public static final int SCARD_ATTR_DEVICE_FRIENDLY_NAME;
    public static final int SCARD_ATTR_DEVICE_SYSTEM_NAME;
    public static final int SCARD_ATTR_SUPRESS_T1_IFS_REQUEST;
    public static final int SCARD_PERF_NUM_TRANSMISSIONS;
    public static final int SCARD_PERF_BYTES_TRANSMITTED;
    public static final int SCARD_PERF_TRANSMISSION_TIME;
    public static final int SCARD_SHARE_EXCLUSIVE = 1;
    public static final int SCARD_SHARE_SHARED = 2;
    public static final int SCARD_SHARE_DIRECT = 3;
    public static final int SCARD_LEAVE_CARD = 0;
    public static final int SCARD_RESET_CARD = 1;
    public static final int SCARD_UNPOWER_CARD = 2;
    public static final int SCARD_EJECT_CARD = 3;

    public WinDefs() {
    }

    static {
        SCARD_ATTR_VENDOR_NAME = Defs.SCARD_ATTR_VENDOR_NAME;
        SCARD_ATTR_VENDOR_IFD_TYPE = Defs.SCARD_ATTR_VENDOR_IFD_TYPE;
        SCARD_ATTR_VENDOR_IFD_VERSION = Defs.SCARD_ATTR_VENDOR_IFD_VERSION;
        SCARD_ATTR_VENDOR_IFD_SERIAL_NO = Defs.SCARD_ATTR_VENDOR_IFD_SERIAL_NO;
        SCARD_ATTR_CHANNEL_ID = Defs.SCARD_ATTR_CHANNEL_ID;
        SCARD_ATTR_PROTOCOL_TYPES = Defs.SCARD_ATTR_PROTOCOL_TYPES;
        SCARD_ATTR_DEFAULT_CLK = Defs.SCARD_ATTR_DEFAULT_CLK;
        SCARD_ATTR_MAX_CLK = Defs.SCARD_ATTR_MAX_CLK;
        SCARD_ATTR_DEFAULT_DATA_RATE = Defs.SCARD_ATTR_DEFAULT_DATA_RATE;
        SCARD_ATTR_MAX_DATA_RATE = Defs.SCARD_ATTR_MAX_DATA_RATE;
        SCARD_ATTR_MAX_IFSD = Defs.SCARD_ATTR_MAX_IFSD;
        SCARD_ATTR_POWER_MGMT_SUPPORT = Defs.SCARD_ATTR_POWER_MGMT_SUPPORT;
        SCARD_ATTR_USER_TO_CARD_AUTH_DEVICE = Defs.SCARD_ATTR_USER_TO_CARD_AUTH_DEVICE;
        SCARD_ATTR_USER_AUTH_INPUT_DEVICE = Defs.SCARD_ATTR_USER_AUTH_INPUT_DEVICE;
        SCARD_ATTR_CHARACTERISTICS = Defs.SCARD_ATTR_CHARACTERISTICS;
        SCARD_ATTR_CURRENT_PROTOCOL_TYPE = Defs.SCARD_ATTR_CURRENT_PROTOCOL_TYPE;
        SCARD_ATTR_CURRENT_CLK = Defs.SCARD_ATTR_CURRENT_CLK;
        SCARD_ATTR_CURRENT_F = Defs.SCARD_ATTR_CURRENT_F;
        SCARD_ATTR_CURRENT_D = Defs.SCARD_ATTR_CURRENT_D;
        SCARD_ATTR_CURRENT_N = Defs.SCARD_ATTR_CURRENT_N;
        SCARD_ATTR_CURRENT_W = Defs.SCARD_ATTR_CURRENT_W;
        SCARD_ATTR_CURRENT_IFSC = Defs.SCARD_ATTR_CURRENT_IFSC;
        SCARD_ATTR_CURRENT_IFSD = Defs.SCARD_ATTR_CURRENT_IFSD;
        SCARD_ATTR_CURRENT_BWT = Defs.SCARD_ATTR_CURRENT_BWT;
        SCARD_ATTR_CURRENT_CWT = Defs.SCARD_ATTR_CURRENT_CWT;
        SCARD_ATTR_CURRENT_EBC_ENCODING = Defs.SCARD_ATTR_CURRENT_EBC_ENCODING;
        SCARD_ATTR_EXTENDED_BWT = Defs.SCARD_ATTR_EXTENDED_BWT;
        SCARD_ATTR_ICC_PRESENCE = Defs.SCARD_ATTR_ICC_PRESENCE;
        SCARD_ATTR_ICC_INTERFACE_STATUS = Defs.SCARD_ATTR_ICC_INTERFACE_STATUS;
        SCARD_ATTR_CURRENT_IO_STATE = Defs.SCARD_ATTR_CURRENT_IO_STATE;
        SCARD_ATTR_ATR_STRING = Defs.SCARD_ATTR_ATR_STRING;
        SCARD_ATTR_ICC_TYPE_PER_ATR = Defs.SCARD_ATTR_ICC_TYPE_PER_ATR;
        SCARD_ATTR_ESC_RESET = Defs.SCARD_ATTR_ESC_RESET;
        SCARD_ATTR_ESC_CANCEL = Defs.SCARD_ATTR_ESC_CANCEL;
        SCARD_ATTR_ESC_AUTHREQUEST = Defs.SCARD_ATTR_ESC_AUTHREQUEST;
        SCARD_ATTR_MAXINPUT = Defs.SCARD_ATTR_MAXINPUT;
        SCARD_ATTR_DEVICE_UNIT = Defs.SCARD_ATTR_DEVICE_UNIT;
        SCARD_ATTR_DEVICE_IN_USE = Defs.SCARD_ATTR_DEVICE_IN_USE;
        SCARD_ATTR_DEVICE_FRIENDLY_NAME = Defs.SCARD_ATTR_DEVICE_FRIENDLY_NAME;
        SCARD_ATTR_DEVICE_SYSTEM_NAME = Defs.SCARD_ATTR_DEVICE_SYSTEM_NAME;
        SCARD_ATTR_SUPRESS_T1_IFS_REQUEST = Defs.SCARD_ATTR_SUPRESS_T1_IFS_REQUEST;
        SCARD_PERF_NUM_TRANSMISSIONS = Defs.SCARD_PERF_NUM_TRANSMISSIONS;
        SCARD_PERF_BYTES_TRANSMITTED = Defs.SCARD_PERF_BYTES_TRANSMITTED;
        SCARD_PERF_TRANSMISSION_TIME = Defs.SCARD_PERF_TRANSMISSION_TIME;
    }
}
